site_name: CheckAAA
site_description: Guia e checklist prático para implementação de UX, Acessibilidade (A11y) e Usabilidade.
site_author: Grupo 09

repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo9
repo_name: IHC_2026.1_Grupo9

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: false

nav:
  - Início: index.md
  - Guia de Acessibilidade:
    - Desenvolvimento Web: desenvolvimentoweb.md
    - Geração de Conteúdo: conteudo.md
    - Design de Interfaces & UX: design.md
    - Heurísticas de Nielsen: heuristicas.md
    - Construção de Personas: personas.md
    - Service Blueprint & Jornada: blueprint.md
    - Design Empático: design_empatico.md
    - Gestão de Projetos & Agilidade: gestao_projetos.md
  - Avaliação do Site:
    - Avaliação Manual (Castelo Forte): avaliacao_castelo_forte.md
    - Avaliação Automatizada com Plugin: relatorio_plugin.md
    - Ferramenta Utilizada (Plugin v3.0): ferramentas.md
    - Template do Relatório: relatorio_template.md
  - Entrevistas:
    - Teste de Usabilidade (Relatório & SUS): teste_usabilidade.md
    - Técnica e Vídeos (Think Aloud): Entrevista/think_aloud.md
    - Roteiro de Entrevista Pós-Teste: Entrevista/roteiro.md
    - Referências Metodológicas: Entrevista/referencias.md