site_name: CheckAAA
site_description: Guia e checklist prático para implementação de acessibilidade.
site_author: Grupo 09

repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo9
repo_name: IHC_2026.1_Grupo9

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

nav:
  - Início: index.md
  - Design: design.md
  - Desenvolvimento Web: desenvolvimento.md
  - Geração de Conteúdo: conteudo.md
  - Gestão de Projetos: gestao.md
  - Nosso Plugin (Ferramenta): ferramentas.md
  - Heurísticas de Nielsen: heuristicas.md