site_name: CheckAAA
site_description: Guia e checklist prático para implementação de UX, Acessibilidade (A11y) e Usabilidade.
site_author: Grupo 09

repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo9
repo_name: IHC_2026.1_Grupo9

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: false

nav:
  - Início: index.md
  - Experiência do Usuário (UX) & Design:
    - Design & Interfaces: design.md
    - Design Empático: design_empatico.md
    - Personas & Jornadas: personas.md
    - Service Blueprint & Canvas: blueprint.md
  - Desenvolvimento & Engenharia:
    - Desenvolvimento Web: desenvolvimentoweb.md
    - Geração de Conteúdo: conteudo.md
    - Gestão de Projetos: gestao_projetos.md
  - Avaliação, Usabilidade & Ferramentas:
    - Heurísticas de Nielsen: heuristicas.md
    - Teste de Usabilidade: teste_usabilidade.md
    - Nosso Plugin (Ferramenta Híbrida): ferramentas.md
    - Template do Relatório: relatorio_template.md
    - Avaliação Manual (Castelo Forte): avaliacao_castelo_forte.md
    - Avaliação Automatizada com Plugin (Castelo Forte): relatorio_plugin.md
  - Pesquisa & Entrevistas:
    - Think Aloud: Entrevista/think_aloud.md
    - Roteiro: Entrevista/roteiro.md
    - Referências: Entrevista/referencias.md